---
# Conflicts with iptables-nft which is required by incus
- name: Remove iptables
  community.general.pacman:
    name: iptables
    state: absent
    force: yes
  become: yes
  when: ansible_os_family == 'Archlinux'

- name: Install incus
  ansible.builtin.package:
    name: incus
    state: present
  become: yes

- name: Add users to incus-admin group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - incus-admin
    append: yes
  loop: "{{ [ansible_user_id] | union(incus_extra_users) }}"
  become: yes

- name: Reload user groups
  ansible.builtin.meta: reset_connection

- name: Start incus service
  ansible.builtin.systemd:
    name: incus.service
    state: started
    enabled: yes
  become: yes

- name: Get old incus config
  ansible.builtin.command:
    cmd: incus admin init --dump
  register: incus_old_config
  changed_when: false

- name: Update incus config
  ansible.builtin.shell:
    cmd: incus admin init --preseed && incus admin init --dump
    stdin: "{{ incus_config | to_yaml }}"
  register: incus_new_config
  changed_when: incus_old_config.stdout != incus_new_config.stdout
  notify: restart_incus

- name: Define subuid/subgid files
  ansible.builtin.template:
    src: subid.j2
    dest: "/etc/{{ item }}"
    mode: 0644
  loop:
    - subuid
    - subgid
  become: yes
  notify: restart_incus

- name: Set lxc default config
  ansible.builtin.template:
    src: lxc.conf.j2
    dest: /etc/lxc/default.conf
    mode: 0644
  become: yes
  notify: restart_incus
